config/routes.rb
Rails.application.routes.draw do
  
  root to: 'welcome#new'
  default_url_options :host => "http://localhost:3000"
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout", :sign_up => "register" }
  match '/users/:id/destroy', to: 'users#destroy', via: [:get, :patch], as: 'signout'
  
  resources :postjobs
  resources :welcome
  resources :jobseeker_dashboard,only: [:index] do
    member do
      get :apply_form
      post :submit_form
    end
  end
  resources :employer_dashboard, only: [:index] do
    collection do
      get :new_company
      post :create_company
      get :edit_company
      put :update_company
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :post_jobs

  validates :user_id, presence: true

end

app/models/postjob.rb
class Postjob < ApplicationRecord
  belongs_to :company

  validates :company_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AppConstants
  helper_method :employer?, :jobseeker?,:logged_in?
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  def employer?
    self.try(:account_type) == EMPLOYER
  end

  def jobseeker?
    self.try(:account_type) == JOBSEEKR
  end
  def logged_in?
    current_user
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:account_type])
  end
  
end

app/controllers/employer_dashboard_controller.rb
class EmployerDashboardController < ApplicationController
  
  def index
  
  end
  
  def new_company
    @company=Company.new
  end
  
  def create_company
    @company = Company.new(company_params)
    @company.save
    redirect_to new_postjob_url
  end
  
  def show_company
    @company = Company.find(params[:id])
  end

  def edit_company
    @company = current_user.company
  end
  def update_company
    @company = current_user.company
    @company.update(company_params)
    redirect_to employer_dashboard_index_path
  end
  private
  def company_params
    params.require(:company).permit(:name, :number_of_employee,:location, :website, :phone, :jobs,:user_id)
  
  end
end

app/controllers/jobseeker_dashboard_controller.rb
class JobseekerDashboardController < ApplicationController
  
  def index
    @jobs=Postjob.all
  end
  
  def apply_form
    @job_id=params[:id]
  end
  
  def submit_form
    @file  = params[:apply][:uploaded_file].path
    job = Postjob.find(params[:apply][:job_id])
    email = job.company.user.email
    @subject = "Job Applicant CV"
    @body = "My name is #{params[:apply][:applicant_name]}.This is my email address #{params[:apply][:email]}.My current salary is #{params[:apply][:current_salary]}.
             and my expected salary is #{params[:apply][:expected_salary]}.Thank you "
    JobEmail.welcome_email(email , @body, @subject, @file).deliver_now
    redirect_to jobseeker_dashboard_index_path, notice: 'you had applied sucessfully'
  end
end

app/controllers/postjobs_controller.rb
class PostjobsController < ApplicationController
  
  def new
    if current_user.company.present?
      @company_id=current_user.company.id
    else
      redirect_to new_company_employer_dashboard_index_path  , notice: "please Register your company first"
    end
    
  end
  
  def create
    
    @job = Postjob.new(job_params)
    @job.save
    redirect_to postjobs_path
  end
  
  def index
    @jobs = Postjob.all
  
  end
  
  def show
    
    @job = Postjob.find(params[:id])
  end
  
  def edit
    @job = Postjob.find(params[:id])
  end
  
  def update
    @job = Postjob.find(params[:id])
    @job.update(job_params)
    redirect_to postjobs_path
  end
  
  def destroy
    @job = Postjob.find(params[:id])
    @job.destroy
    redirect_to postjobs_path
  end
  
  private
  def job_params
    params.require(:job).permit(:job_title, :job_description, :company_name, :skills, :qualification, :experience, :salary, :company_id)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  
  end

  def new
    if logged_in?
      if current_user.account_type == "EMPLOYER"
        redirect_to employer_dashboard_index_path
      else
        redirect_to jobseeker_dashboard_index_path
      end
    else
      redirect_to new_user_session_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employer_dashboard_helper.rb
module EmployerDashboardHelper
end

app/helpers/jobseeker_dashboard_helper.rb
module JobseekerDashboardHelper
end

app/helpers/postjobs_helper.rb
module PostjobsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employer_dashboard/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top">
        <i class="fa fa-play-circle"></i> <span class="light">Welcome to</span> Job Site
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li style="padding-top: 15px;">
          <span> Welcome! </span> <%= current_user.email %>
        </li>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/employer_dashboard/edit_company.html.erb
<%=render partial: 'navbar' %>
<div>
  <h3>Update your company info</h3>
  <div align="center" >
    <%= form_for :company, url: update_company_employer_dashboard_index_path(@company), method: :put do |f| %>


        <p>
          <%= f.label :name, value="Company Name" %><br>
          <%= f.text_field :name, class:"formClass" %>
        </p>

        <p>
          <%= f.label :number_of_employee,value="Size of company" %><br>
          <%= f.text_field :number_of_employee,class:"formClass" %>
        </p>
        <p>
          <%= f.label :location, value="Address" %><br>
          <%= f.text_area :location, class:"formClass" %>
        </p>
        <p>
          <%= f.label :website, value="Company URL" %><br>
          <%= f.text_field :website, class:"formClass" %>
        </p>
        <p>
          <%= f.label :phone, value="Company Number" %><br>
          <%= f.text_field :phone, class:"formClass" %>
        </p>
        <p>
          <%= f.label :jobs, value="Number of vacancies" %><br>
          <%= f.text_field :jobs, class:"formClass" %>
        <p>
        <p>
          <%= f.hidden_field :user_id, :value => current_user.id %>
        </p>

        <p>
          <%= f.submit "Update company", class: "form-control submitBtn", value: "Create company" %>
        </p>
    <% end %>
  </div>
</div>
<style>
  .formClass{
    color:#000000;
  }
  .submitBtn{
    width: 10%;
  }
</style>

app/views/employer_dashboard/index.html.erb
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top">
        <i class="fa fa-play-circle"></i> <span class="light">Welcome to</span> Job Site
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
          <%= link_to "Post job", new_postjob_path,class:"page-scroll"%>
        </li>
        <li>
          <!--<a class="page-scroll" href="#Post a job">Post a Job</a>-->
          <% if current_user.company.present? %>
              <%= link_to "Edit  company Info", edit_company_employer_dashboard_index_path,class:"page-scroll"%>
              <% else %>
          <%= link_to "Registe your company", new_company_employer_dashboard_index_path,class:"page-scroll"%>
              <% end %>
        </li>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/employer_dashboard/new_company.html.erb
<%=render partial: 'navbar' %>
<div>
  <h1>Register your company here</h1>
  <div align="center" >
    <%= form_for :company, url: create_company_employer_dashboard_index_path do |f| %>


        <p>
          <%= f.label :name, value="Company Name" %><br>
          <%= f.text_field :name, class:"formClass" %>
        </p>

        <p>
          <%= f.label :number_of_employee, value="Size of company" %><br>
          <%= f.text_field :number_of_employee,class:"formClass" %>
        </p>
        <p>
          <%= f.label :location, value="Address" %><br>
          <%= f.text_area :location, class:"formClass" %>
        </p>
        <p>
          <%= f.label :website, value="Company URL" %><br>
          <%= f.text_field :website, class:"formClass" %>
        </p>
        <p>
          <%= f.label :phone, value="Company Number" %><br>
          <%= f.text_field :phone, class:"formClass" %>
        </p>
        <p>
          <%= f.label :jobs, value="Number of vacancies" %><br>
          <%= f.text_field :jobs, class:"formClass" %>
        <p>
        <p>
          <%= f.hidden_field :user_id, :value => current_user.id %>
        </p>

        <p>
          <%= f.submit "Create company", class: "form-control submitBtn", value: "Create company" %>
        </p>
    <% end %>
  </div>
</div>
<style>
  .formClass{
    color:#000000;
  }
  .submitBtn{
    width: 10%;
  }
</style>

app/views/employer_dashboard/show_company.html.erb
<%=render partial: 'navbar' %>
<div class="row">
  <div class="col-sm-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>Available Jobs</h5>
      </div>
      <div class="ibox-content">
        <table class="table table-bordered favs-list">
          <thead>
          <tr>
            <th>
              Company Name
              <i class="fa fa-caret-down pull-right"></i>
            </th>
            <th>
              Size of Company
              <i class="fa fa-caret-down pull-right"></i>
            </th>
            <th>
              Address
              <i class="fa fa-caret-down pull-right"></i>
            </th>
            <th>
              website
              <i class="fa fa-caret-down pull-right"></i>
            </th>
            <th>
              Contact Number
              <i class="fa fa-caret-down pull-right"></i>
            </th>
            <th>
              Vacancies
              <i class="fa fa-caret-down pull-right"></i>
            </th>
          </tr>
          </thead>
          <tbody>
          <% @company.each do |company| %>
              <tr class="gradeX">
                <td min_width="50%;">
                  <%= company["name"] %>
                </td>
                <td>
                  <%= company["number_of_employee"] %>
                </td>
                <td class="text-center">
                  <%= company["location"] %>
                </td>
                <td class="text-center">
                  <%= company["website"] %>
                </td>
                <td class="text-center">
                  <%= company["phone"] %>
                </td>
                <td class="text-center">
                  <%= company["jobs"] %>
                </td>

              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<script>
  $('.hello').dataTable();
</script>

app/views/jobseeker_dashboard/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top">
        <i class="fa fa-play-circle"></i> <span class="light">Welcome to</span> Job Site
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
          <!--<a class="page-scroll" href="#Post a job">Post a Job</a>-->
          <% if current_user.account_type == 'EMPLOYER ' %>
              <%= link_to "Post a Job", new_postjob_path,class:"page-scroll"%>
          <% end %>
        </li>
        <li style="padding-top: 15px;">
          <span> Welcome! </span> <%= current_user.email %>
        </li>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/jobseeker_dashboard/apply_form.html.erb
<div>
  <h3>Apply for job</h3>
  <div align="center">
    <%= link_to 'Back', :back %>
    <%= form_for :apply, url: submit_form_jobseeker_dashboard_path do |f| %>
        <p>
          <%= f.label :applicant_name, value="Enter your Name" %><br>
          <%= f.text_field :applicant_name, class: "formClass" %>
        </p>
        <p>
          <%= f.label :email, value="Enter your Email" %><br>
          <%= f.text_field :email, class: "formClass" %>
        <p>
          <%= f.label :current_salary, value="Current Salary" %><br>
          <%= f.text_field :current_salary, class: "formClass" %>
        </p>
        <p>
          <%= f.label :expected_salary, value="Expected Salry" %><br>
          <%= f.text_field :expected_salary, class: "formClass" %>
        </p>
        <%= f.label :uploaded_file, 'Upload only pdf file'%>
        <%= f.file_field :uploaded_file%>
          <%= f.submit "Apply job", class: "form-control submitBtn", value: "Apply Job" %>
        </p>
        <p>
        <p>
          <%= f.hidden_field :job_id, :value => @job_id %>
        </p>
        </p>
    <% end %>
  </div>
</div>
<style>
  .formClass {
    color: #000000;
  }

  .submitBtn {
    width: 10%;
  }
</style>

app/views/jobseeker_dashboard/index.html.erb
<%= render partial: 'navbar' %>
<div class="row">
  <div class="col-sm-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>Available Jobs</h5>
      </div>
      <div class="ibox-content">
        <table class="table table-bordered favs-list">
          <thead>
          <tr>
            <th>
              Sr.No
              <i class="fa fa-caret-down pull-right"></i>
            </th>
            <th>
              Job Title
              <i class="fa fa-caret-down pull-right"></i>
            </th>
            <th>
              Company Name
              <i class="fa fa-caret-down pull-right"></i>
            </th>
            <th>
              Action
              <i class="fa fa-caret-down pull-right"></i>
            </th>
          </tr>
          </thead>
          <tbody>
          <% @jobs.each_with_index do |job| %>
              <tr class="gradeX">
                <td min_width="50%;">
                  <%= job["id"] %>
                </td>
                <td>
                  <%= job["job_title"] %>
                </td>
                <td class="text-center">
                  <%= job["company_name"] %>
                </td>
                <td class="text-center">
                  <%= link_to "View",postjob_path(job["id"]) %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<script>
  $('.hello').dataTable();
</script>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
  <div class="footer-left-panel">
    <p>© 2017 Job Site</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Intro Header -->
<header class="intro">
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h1 class="brand-heading">Job Site</h1>
          <p class="intro-text">You can post a job or you can get hire.<br>Created originally by Ferhan Nasim.</p>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top">
        <i class="fa fa-play-circle"></i> <span class="light">Welcome to</span> Job Site
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
          <!--<a class="page-scroll" href="#Post a job">Post a Job</a>-->
          <%= link_to "Post a Job", new_postjob_path,class:"page-scroll"%>
        </li>
        <li>
          <%= link_to "Get Hired", postjobs_path,class:"page-scroll"%>
        </li>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/postjobs/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top">
        <i class="fa fa-play-circle"></i> <span class="light">Welcome to</span> Job Site
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
          <%= link_to 'Back', :back %>
        </li>
        <li>
          <!--<a class="page-scroll" href="#Post a job">Post a Job</a>-->
          <% if current_user.account_type == 'EMPLOYER' %>
          <%= link_to "Post a Job", new_postjob_path,class:"page-scroll"%>
              <% end %>
        </li>
        <li style="padding-top: 15px;">
          <span> Welcome! </span> <%= current_user.email %>
        </li>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/postjobs/edit.html.erb
<%= render partial: 'navbar' %>
<div>
  <h1>Edit info</h1>
  <div align="center">
    <%= form_for :job, url: postjob_path(@job), method: :patch do |f| %>
        <p>
          <%= f.label :job_title, value="Job Title" %><br>
          <%= f.text_field :job_title, class: "formClass" %>
        </p>

        <p>
          <%= f.label :job_description, value="Job Description" %><br>
          <%= f.text_area :job_description, class: "formClass" %>
        </p>
        <p>
          <%= f.label :company_name, value="Company Name" %><br>
          <%= f.text_field :company_name, class: "formClass" %>
        </p>
        <p>
          <%= f.label :skills, value="Skills required" %><br>
          <%= f.text_field :skills, class: "formClass" %>
        </p>
        <p>
          <%= f.label :qualification, value="Qualification" %><br>
          <%= f.select :qualification, ['Non-Matriculation', 'Matriculation/O-Level', 'Intermediate/A-Level', 'Bachelors', 'Masters', 'Certification', 'PHD/Doctorate'], :prompt => 'Select One', class: "formClass" %>
        </p>
        <p>
          <%= f.label :experience, value="Experiance Required" %><br>
          <%= f.select :experience, ['Fresh', '1+', '2+', '3+', '4+', '5+'], :prompt => 'Select One', class: "formClass" %>
        <p>
          <%= f.label :salary, value="Salray range" %><br>
          <%= f.select :salary, ['5k-10k', '10k-20k', '20k-30k', '30k-40k', '40k-50k', '50-60k', '60k-70k', '70k-80k', '80k-90k', '90k-100k', '100k+'], :prompt => 'Select One', class: "formClass" %>
        </p>
        <p>
          <%= f.submit "Update job", class: "form-control submitBtn", value: "Post Job" %>
        </p>
    <% end %>
  </div>
</div>
<style>
  .formClass {
    color: #000000;
  }

  .submitBtn {
    width: 10%;
  }
</style>

app/views/postjobs/index.html.erb
<%=render partial: 'navbar' %>
<div class=" col-sm-4">
  <h3>Available Jobs</h3>
  <table>
    <thead>
    <th>Sr.#</th>
    <th>Job Title</th>
    <th>Job Description</th>
    <th>Company Name</th>
    <th>Actions</th>
    </thead>
    <tbody>
    <% @jobs.each_with_index do |job| %>
        <tr>
          <td>
            <%= job["id"] %>
          </td>
          <td>
            <%= job["job_title"] %>
          </td>
          <td>
            <%= job["job_description"] %>
          </td>
          <td>
            <%= job["company_name"] %>
          </td>
          <td>
            <%= link_to "View",postjob_path(job["id"]) %>
            <%= "||" %>
            <%= link_to "Edit",edit_postjob_path(job["id"]) %>
            <%= "||" %>
            <%= link_to "Delete", postjob_path(job[:id]),  method: :delete, data: { confirm: 'Are you sure to delete this post ?' } %>

          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%= render 'layouts/footer' %>

app/views/postjobs/show.html.erb
<%= render partial: 'navbar' %>
<div class="row">
  <div class="col-sm-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h4>Job Details</h4>
      </div>
      <div class="ibox-content">
        <table class="table table-bordered favs-list">
          <thead>
          <tr>
            <th>
              Job Title
              <i class="fa fa-caret-down pull-right"></i>
            </th>
            <th>
              Job Description
              <i class="fa fa-caret-down pull-right"></i>
            </th>
            <th>
              Company Name
              <i class="fa fa-caret-down pull-right"></i>
            </th>
            <th>
              Skills required
              <i class="fa fa-caret-down pull-right"></i>
            </th>
            <th>
              Qualification
              <i class="fa fa-caret-down pull-right"></i>
            </th>
            <th>
              Experiance Rquired
              <i class="fa fa-caret-down pull-right"></i>
            </th>
            <th>
              Salary Range
              <i class="fa fa-caret-down pull-right"></i>
            </th>
            <% if current_user.account_type == 'JOBSEEKR' %>
          <th>
              Action
              <i class="fa fa-caret-down pull-right"></i>
            </th>
                <% end %>
          </tr>
          </thead>
          <tbody>
          <tr class="gradeX">
            <td min_width="50%;">
              <%= @job["job_title"] %>
            </td>
            <td>
              <%= @job["job_description"] %>
            </td>
            <td class="text-center">
              <%= @job["company_name"] %>
            </td>
            <td class="text-center">
              <%= @job["skills"] %>
            </td>
            <td class="text-center">
              <%= @job["qualification"] %>
            </td>
            <td class="text-center">
              <%= @job["experience"] %>
            </td>
            <td class="text-center">
              <%= @job["salary"] %>
            </td>
            <% if current_user.account_type == 'JOBSEEKR' %>
            <td class="text-center">
              <%= link_to "Apply ",apply_form_jobseeker_dashboard_path(@job["id"]) %>
            </td>
                <% end %>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<script>
  $('.hello').dataTable();
</script>

app/views/welcome/index.html.erb
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top">
        <i class="fa fa-play-circle"></i> <span class="light">Welcome to</span> Job Site
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
          <!--<a class="page-scroll" href="#Post a job">Post a Job</a>-->
          <%= link_to "Post a Job", new_postjob_path,class:"page-scroll"%>
        </li>
        <li>
          <%= link_to "Get Hired", postjobs_path,class:"page-scroll"%>
        </li>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>